name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          CIBW_PRERELEASE_PYTHONS: True
          CIBW_SKIP: pp*
          CIBW_BEFORE_ALL_MACOS: brew install libmpc
          CIBW_BEFORE_BUILD: bash scripts/before_ci_build.sh
          CIBW_ARCHS_MACOS: "auto arm64"

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse
