name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, macos-14]
    steps:
      - uses: actions/checkout@v3
      - if: runner.os == 'macOS'
        run: brew install pipx
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_PRERELEASE_PYTHONS: True
          CIBW_SKIP: pp*
          CIBW_BEFORE_BUILD: bash scripts/cibw_before_all.sh
          CIBW_TEST_EXTRAS: tests
          CIBW_TEST_COMMAND: >
            pytest {package}/test/ &&
            python {package}/test_cython/runtests.py
          CIBW_REPAIR_WHEEL_COMMAND: >
            bash scripts/cibw_repair_wheel_command.sh {dest_dir} {wheel}
      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse
