name: pip_install_gmpy2

on: [push, pull_request]

jobs:
  osx:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install --upgrade pip
      - run: pip --verbose install -e .
      - run: python test/runtests.py

  linux:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      #   Don't build documentation by default.
      # - run: sudo apt-get install libmpc-dev texlive texlive-latex-extra latexmk
      - run: sudo apt-get install libmpc-dev
      - run: pip install --upgrade pip
      - run: pip --verbose install -e .
      - run: python test/runtests.py
