name: pip_install_gmpy2

on: [push, pull_request]

jobs:
  osx:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11, '3.12-dev']
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install --upgrade pip
      - run: pip --verbose install -e .[cython]
      - run: python test/runtests.py
      - run: PYTHONPATH=`pwd`/gmpy2 python test_cython/runtests.py
        if: ${{ matrix.python-version == '3.11' }}

  linux:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - run: sudo apt-get install libmpc-dev texlive texlive-latex-extra latexmk
      - run: pip install --upgrade pip
      - run: pip --verbose install -e .[cython,docs]
      - run: python test/runtests.py
      - run: PYTHONPATH=`pwd`/gmpy2 python test_cython/runtests.py
      - run: sphinx-build --color -W --keep-going -b doctest docs build/sphinx/doctest
      - run: sphinx-build --color -W --keep-going -b html docs build/sphinx/html
      - run: sphinx-build --color -W --keep-going -b latex docs build/sphinx/latex
      - run: make -C build/sphinx/latex all-pdf
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            build/sphinx/doctest/
            build/sphinx/html/
            build/sphinx/latex/gmpy2.pdf
